// Both native signers (Swift and Kotlin) hardcode the routable-seal and ECDH goldens generated by
// scripts/gen-routable-golden.ts / gen-ecdh-golden.ts and checked into ios/*.golden.json. This pins
// every fixture value to BOTH sources so neither can drift from the TS oracle — and it pins the
// Kotlin unit test's public-key/fingerprint expectations to what @noble produces right now.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { p256 } from '@noble/curves/p256';
import { sha256 } from '@noble/hashes/sha256';

const MOD = join(import.meta.dirname, '..', '..', 'modules', 'expo-passive-entry');
const swift = readFileSync(join(MOD, 'ios', 'VcsecSigner.swift'), 'utf8').toLowerCase();
const kotlin = readFileSync(join(MOD, 'android', 'src', 'main', 'java', 'expo', 'modules', 'passiveentry', 'VcsecSigner.kt'), 'utf8').toLowerCase();
const kotlinTest = readFileSync(
  join(MOD, 'android', 'src', 'test', 'java', 'expo', 'modules', 'passiveentry', 'VcsecSignerTest.kt'),
  'utf8',
).toLowerCase();

const seal = JSON.parse(readFileSync(join(MOD, 'ios', 'routableSeal.golden.json'), 'utf8')) as {
  inputs: Record<string, string | number>;
  aadHex: string;
  ciphertextHex: string;
  tagHex: string;
  frameHex: string;
};
const ecdh = JSON.parse(readFileSync(join(MOD, 'ios', 'ecdh.golden.json'), 'utf8')) as {
  myPrivHex: string;
  peerPubHex: string;
  sessionKeyHex: string;
};

test('routable-seal golden outputs are hardcoded identically in the Swift and the Kotlin signer', () => {
  for (const [name, hex] of Object.entries({
    aad: seal.aadHex,
    ciphertext: seal.ciphertextHex,
    tag: seal.tagHex,
    frame: seal.frameHex,
  })) {
    assert.ok(swift.includes(hex.toLowerCase()), `Swift is missing the ${name} golden`);
    assert.ok(kotlin.includes(hex.toLowerCase()), `Kotlin is missing the ${name} golden`);
  }
});

test('routable-seal golden inputs (vin, nonce, inner) appear in both signers', () => {
  const { vin, nonce, innerHex } = seal.inputs as { vin: string; nonce: string; innerHex: string };
  for (const needle of [vin.toLowerCase(), nonce.toLowerCase(), innerHex.toLowerCase()]) {
    assert.ok(swift.includes(needle), `Swift is missing input ${needle}`);
    assert.ok(kotlin.includes(needle), `Kotlin is missing input ${needle}`);
  }
});

test('ECDH golden peer key and session key are hardcoded identically in both signers', () => {
  for (const hex of [ecdh.peerPubHex, ecdh.sessionKeyHex]) {
    assert.ok(swift.includes(hex.toLowerCase()), `Swift is missing ${hex.slice(0, 12)}…`);
    assert.ok(kotlin.includes(hex.toLowerCase()), `Kotlin is missing ${hex.slice(0, 12)}…`);
  }
});

test('the Kotlin unit test expects exactly the public key and fingerprint noble derives for the golden scalar', () => {
  const priv = Uint8Array.from(Buffer.from(ecdh.myPrivHex, 'hex'));
  const pub = p256.getPublicKey(priv, false);
  const pubHex = Buffer.from(pub).toString('hex');
  const fingerprint = Array.from(sha256(pub).slice(0, 8), (b) => b.toString(16).padStart(2, '0')).join(':');
  assert.ok(kotlinTest.includes(pubHex), 'VcsecSignerTest.kt public-key expectation drifted from noble');
  assert.ok(kotlinTest.includes(fingerprint), 'VcsecSignerTest.kt fingerprint expectation drifted from noble');
});
